### ISSUE TITLE
Most topics do not show in-use storage

### ISSUE THREAD

**Issue by ChrisTVH** [TheFonix/Pterodactyl-Themes#20] opened 2020-05-05 04:26 UTC
Most topics don't show in-use storage the only thing that comes out is ```-- %```
I would like them to fix that

**Comment by lstefan1520** [comment] 2020-05-05 19:27
I was able to reproduce this aswell:
![image](https://user-images.githubusercontent.com/44349634/81107285-ed1cd980-8ee4-11ea-9967-3f631ad58250.png)

**Comment by Liyf4TakingLs** [comment] 2020-08-22 21:56
Hello, I've found a quick fix for that issue. This fix is only for Disk Usage @ ServerList.... (Does not fix any Admin Problems.)
Simply replace the /var/www/pterodactyl/public/themes/pterodactyl/js/frontend/serverlist.js code with : 
https://github.com/pterodactyl/panel/blob/release/v0.7.18/public/themes/pterodactyl/js/frontend/serverlist.js
That should fix the issue.
![image](https://user-images.githubusercontent.com/43788244/90966471-074de800-e4d3-11ea-9c47-fb5beca615e7.png)
Best Regards.


Also I do not recommend using any themes since they will break & give 500 Error. Use at your own risk.

**Comment by TheFonix** [comment] 2020-09-20 10:33
This will be fixed in the new release of the themes. Also @Liyf4TakingLs The new update will not cause internal servers errors as it will not touch any of the fundamental JS or PHP files, it will only overwrite the CSS files. As well as the script re-doing the permissions after its finished. :)

**Closed as completed by TheFonix** 2020-09-20 10:33 UTC
